# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $HOME/.config/p10k.zsh ]] || source $HOME/.config/p10k.zsh

# only put cwd on tab/window title
export DISABLE_AUTO_TITLE="true"
precmd () {print -Pn "\e]0;%~\a"}

# kubectl autocomplete
source <(kubectl completion zsh)
compdef __start_kubectl k

# Add user controlled ad hoc bin directories to front of PATH, ensures that 
# these binaries take precedence over nix-provided binaries when they conflict,
# allowing quick and dirty testing of dev builds, etc.
export PATH="$HOME/bin:$GOBIN:$PATH"

# fzf powered shell history
h() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac +x -e --height "50%" | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}